# Generated by Django 5.1 on 2024-09-05 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='imageUrl',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='linkcode',
            new_name='link_code',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='longName',
            new_name='long_name',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='objectid',
            new_name='object_id',
        ),
    ]
