# Generated by Django 5.1 on 2024-09-05 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_picture'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UserCountry', to='master.country'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_years',
            field=models.IntegerField(default=2),
        ),
    ]
